name: 'airflow_analytics'
version: '1.0.0'

profile: 'airflow_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  airflow_analytics:
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
